name: macopilot

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  x64_Release:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo tauri build
  arm64_Release:
    runs-on: macos-13-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo tauri build
