name: macopilot

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Release:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Pre-build
      run: cargo install tauri-cli
    - name: Build
      run: cargo tauri build
